### ISSUE TITLE
mount locally a user  directory through ssh

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#10]
Is there a way to mount locally a user directory through ssh? That would make it very convenient to move files back and forth between the NextBox and the computer host :) .

**Comment by daringer** [comment]
Locally you can easily use `sshfs` to mount a path through ssh.

* Your user's files should be at: `/srv/nextcloud/data/<username>/files`
* You will also need to use the root user for this (or update groups for nextuser),  as the stock nextuser will have no permissions to access these files.
* Do not change the file-permissions of any file inside `/srv`, because this will likely lead non-deterministic behavior.
