### ISSUE TITLE
Provide currently delivered NextBox image as download

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nextbox#15]
To allow DIY nextbox, 

blocks the DIY documentation: https://github.com/Nitrokey/nitrokey-documentation/issues/38

**Comment by daringer** [comment]
https://www.nitrokey.com/files/ci/nextbox/

**Comment by jerabaul29** [comment]
Thanks for adding this to the documentation todo :) . I think adding the link to the image from the documentation with a specific documentation entry would be perfect :) .

A small note: could you, on your webside page pointing to the image, add a cryptographic hash value of the image in order to be able to check its integrity? :) .

**Comment by daringer** [comment]
puh this took long, done ;)
