### ISSUE TITLE
connecting on local network: only able to use http, not https

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#2]
I just received my nextbox and put it into service now. It works well, so this is great :) .

However there is one point I was worried / disappointed about. It looks like I can reach the ```nextbox.local``` site only in http protocol, not in https protocol. While the nextbox is only connected on my local network, I still do not like it. Any reason why the nextbox is only accessible through http / any ways to use https instead / how to fix this?

**Comment by jerabaul29** [comment]
PS: not sure this is the right location, let me know if I should move to https://github.com/Nitrokey/nextbox-app/issues .

**Comment by daringer** [comment]
Perfectly fine to have this issue here.

To your point: One important property of `https://` is that a CA (https://en.wikipedia.org/wiki/Certificate_authority) is able to verify that a certain certificate is used (and valid) only in combination with a public accessible domain. In fact this not only ensures that the traffic is encrypted, but also gives you the user the safety that the traffic is originating from the owner of the domain (and not from some e.g., attacker).

So to have a proper https (TLS) connection you roughly go these steps: 
* get a public available domain
* ask a CA you to verify that this public domain is available
* acquire a TLS certificate for this public domain

these steps are partly automated within the NextBox using e.g., guided DNS.

There also is the possibility to use a so-called self-signed certificate, which will indeed encrypt the traffic, but as not verifiable with a CA your browser will issue a warning and generally warn you the user to visit this page. (as it cannot be ensured where the traffic originates)

Once you activate one of the dynamic/static DNS methods you can acquire a certificate for your domain and then the non-encrypted "http" access to your NextBox will generally be switched off.

hope this explains it a little
best

**Comment by jerabaul29** [comment]
Ok, thanks, so then I think if I understand well that the best solution would be that 1) set up the Guided Dynamic DNS Configuration 2) this should allow to enable https et co, right? :) .

I wonder if this may / "should" be the standard setup for nextcloud installation. Sounds scary to have http traffic on wireless networks, right?

**Comment by daringer** [comment]
> Ok, thanks, so then I think if I understand well that the best solution would be that 1) set up the Guided Dynamic DNS Configuration 2) this should allow to enable https et co, right? :) .

yep right

> I wonder if this may / "should" be the standard setup for nextcloud installation. Sounds scary to have http traffic on wireless networks, right?

This is why we recommend this, but it is not possible to do this upfront (or just with very high efforts) as this always involves the registration of a domain and acquiring of the certificate.

**Comment by jerabaul29** [comment]
> This is why we recommend this, but it is not possible to do this upfront (or just with very high efforts) as this always involves the registration of a domain and acquiring of the certificate.

Could this be solved by an "onboarding process"? I.e., rather than "just" asking for a username and password for admin, 1) send the user to / ask for the necessary DNS stuff, 2) register with both admin username, password, and all the necessary information to set up the DNS and certificate stuff?

**Comment by jerabaul29** [comment]
I think this would be really helpful to make the default secure for people "even n00ber than myself" :) .

**Comment by daringer** [comment]
It will be pretty tough to change the default first setup from nextcloud, but we already have on the list to be more pushy towards the user to setup a TLS encryption + dns, likely also through e.g., notifications, but enforcing this to the user is something we cannot do, as still there might be users who simply do not want to have their NextBox available through the internet.

Additionally for setting up a proper TLS encrypted NextBox/Nextcloud you'll need to configure port forwarding on your internet router, this is also something we cannot (reliably) do from within Nextcloud.

So I am afraid making this fully default will not be possible

**Comment by jerabaul29** [comment]
Ok, I see, thanks.

**Comment by daringer** [comment]
compiled this into this issue: https://github.com/Nitrokey/nextbox-daemon/issues/15
further extended the documentation with some bits of this thread: https://docs.nitrokey.com/nextbox/remote/method-comparison.html
