### ISSUE TITLE
Option for 2FA / TOTP with the SSH access

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#27]
Would it be possible in the Nextbox app to offer the possibility to set up 2FA / TOTP with one tickable box for the SSH access? That would make SSH access a bit safer I guess? :) . I know one can set up SSH with 2FA, would be great to offer an easy way to do it with both Google authenticator app and some 2FA nitrokeys :) .

I think this is the last login / access mechanismto the Nextbox that is not covered with 2FA, since nextcloud login can be set with 2FA through a small additional app.

**Comment by jerabaul29** [comment]
(I have one Nextbox already in 'production' use that I don't want to lock myself out but think about buying an extra low spec one for testing, may help with some testing on this kind of features).

**Comment by daringer** [comment]
It's pretty straight forward to use e.g., the Nitrokey FIDO2 for ssh logins. But sure that's no 2FA, quite some time passed since I've been playing around with 2FA for ssh, might be worth to check. But on the other side, the added value compared to a security token like FIDO2 or the NK Pro2 is .... marginal I guess

**Comment by daringer** [comment]
cleaning up, feel free to reopen
