### ISSUE TITLE
"Backwards Proxy Remote Access for Your NextBox" not end to end encrypted - help understanding

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#4]
I have set up the "Backwards Proxy Remote Access for Your NextBox", but I read on the nitrokey website that this is not end to end encrypted. I am trying to understand why and what this implies.

- does this well mean that the traffic is encrypted between my nextbox and your proxy server, and then between your proxy server and my accessing endpoints, but not from my nextbox to the accessing endpoint directly? I.e. that means that I have to trust you, but that as long as I do, all should be fine, right?

- is there a fundamental technical reason for not having end to end encryption with the backwards proxy remote access method? Is this just something that needs to be implemented, or is there a fundamental reason that makes end to end encryption impossible with this method?

**Comment by jerabaul29** [comment]
PS: not sure this is the right location, let me know if I should move to https://github.com/Nitrokey/nextbox-app/issues .

**Comment by daringer** [comment]
With end-to-end encryption the key property is that between sender and receiver nobody is decrypting the traffic. this property is violated with the backwards proxy as technically there are 2 end-to-end connections chained ....
so your traffic is end-to-end encrypted between your client and our proxy... on the proxy the traffic decrypted and forwarded to your nextbox ... this connection between the proxy and your nextbox is again end-to-end encrypted.

to you questions:

* yes, generally the backwards proxy means you have to trust us, then you are fine in terms of encrypted traffic (even if formally not end-to-end) 
* trust here means also, that you have to trust our infrastructure, if e.g., the server gets compromised the attacker might have access to your traffic unencrypted
* frankly I cannot tell if there is a proxy concept that supports true end-to-end encryption. From what I know about the CA/TLS/HTTPS concepts this might already be an issue due to the origin property of the TLS encrypted traffic. So the short answer is: as far as I know true end-to-end encryption will not be possible with this backwards proxy approach

**Comment by jerabaul29** [comment]
Ok, I see. Many thanks for your explanations and your help :) .

I was / am still a bit surprised that there is no true end-to-end encryption even though it goes through your proxy servers, and that this is rather chaining two end-to-end encryptions. My "intuition" would tell me that it should be possible to have end-to-end encryption even through your servers, as this is well what happens everyday when I use Whatsapp or Telegram, right? :) . I mean in theory, is this not "just" a question of transfering gpg-encrypted files through the 2 end to end servers, instead of transmitting the raw files through the "double consecutive" end-to-end communication? Or am I missing something? :) .

**Comment by daringer** [comment]
Think you are overseeing the "origin" property, Generally the concepts for messaging e2e encryption do not come with this property (at least not with a CA as far as I know). But overall I am with you, there is for sure a way to realize data-traffic proxies and end-to-end, it was simply also not the design-goal here as this would likely increase complexity a lot for the proxy.

**Comment by jerabaul29** [comment]
Yeah, feels like if I have some really sensitive files and no e2e encryption, I will probably 1) encrypt with GPG on my linux machine 2) save them on my nextbox 3) when I need them, download them fully encrypted from my nextbox and decrypt on my machine. I guess this is some form of e2e with myself then... I am using nitrokeys, so that should not even be too painful to do :)  ^^ . But still, I would prefer stronger defaults (and I think nextbox without strong defaults looses a bit of its point for n00b / intermediate users; what is the point to "break free from GDrive", if you have no e2e...).

**Comment by daringer** [comment]
getting your point, but that's why we suggest to use a dynamic DNS setup + TLS, this will ensure e2e encryption. We'll consider making this more clear in the docs

**Comment by jerabaul29** [comment]
Sounds good :) . Yes agree, the fact that "e2e is only available once the DNS setup + TLS is performed, which is not done by default / not imposed on you, so this is your responsibility as a user to set it up" should come in large bold red on all nextbox UI screens as long as it is not set up by the user :) .

**Comment by daringer** [comment]
partly taken into the docs: https://docs.nitrokey.com/nextbox/remote/method-comparison.html

nofication that no TLS is active issue: https://github.com/Nitrokey/nextbox-daemon/issues/15
