### ISSUE TITLE
backup: having 2 nextboxes checking each other

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nextbox#5]
I would like to have a "smart backup" solution with 2 nextboxes running from different geographical locations checking each other's health and using each other as backup / mirror of my data.

Is there a way so that:

- I can seamlessly connect to my nextcloud
- the data are uploaded on any of my nextboxes, seamlessly for me
- the nextboxes automatically communicate with each other to make sure they mirror each other

Any way this can be attained?

**Comment by jerabaul29** [comment]
PS: not sure this is the right location, let me know if I should move to https://github.com/Nitrokey/nextbox-app/issues .

**Comment by daringer** [comment]
This request comes up a lot and even though it feels like a very natural approach it is not so easy to realize in a proper way. Actually you are asking for a nextcloud-cluster-setup here, which comes with some pretty tough data consistency challenges:

* what happens if a file was changed on both Nextcloud instances at the same time
* what means "at the same time", so how often should the nextcloud instances talk together to find out if files/data/database contents have been changed

here is a thread touching this topic: https://help.nextcloud.com/t/help-me-test-this-3-node-cluster/12863/23
and also generally this feature is considered an enterprise Nextcloud feature

so overall what I can say that we are looking into other possibilities to realize backups in the future, but I have doubts that such a "mirror my nextbox to another nextbox" feature is realisitic.

**Comment by jerabaul29** [comment]
I see. Sorry for missing the forum discussion. I am just tired of so many forums all the time, so trying to default to github issues :) .

I understand that "solving it very professionally" is tough, as you point out - and usually, private users will anyways not be needing that / not building a true, full cloud system as you say :) . But would there not be some slightly less bullet proof solution, like having maybe only 1 nextbox used as the "main mode" nextbox as any nextbox would be used when it is installed, and another nextbox in "mirror mode" taking a backup of the first one each hour with some form of rsync? As long as there is a simple switch to change the mode of my nextboxes between master and mirror, and maybe a bit of automatic consistency checks in which mode is activated where, that would be more than enough to me.

**Comment by daringer** [comment]
Yap, we are looking into exactly these compromises for advanced backup features, but cannot promise any particular right now...

**Comment by jerabaul29** [comment]
Sounds very good, will be looking forward to this very much :) .

A bit chit chat, but: personally, I will not fully use my nextbox(es) for keeping my personal data before this is put in place. I have seen too much stuff dying at work to trust my private data being safe with a single nextbox, or even with a single nextbox connected to an additional external HDD for backup but in the same location. We had a solution like this at one of my old workplaces, that was supposed to be "safe". Until the day there was over tension in the server room that fried a whole bunch of HDDs at once and we actually lost a lot of data. So now I will never again trust that I have "safe" data storing without having 2 automatic copies of it in 2 quite distinct geographical locations :) .

**Comment by daringer** [comment]
Please keep in mind that using the Nextcloud app implies local copies of all (logged in user) files, so by having multiple clients you also mitigate some of the risk. Still this means "only" the data can be recovered, the settings (e.g., database) is not copied at all. Means disaster recovery will be bound to more work compared to a "real" backup ...

Nevertheless, I am closing this issue in favor of https://github.com/Nitrokey/nextbox-daemon/issues/14 where the "advanced backup features" will be tracked
