### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by praxrex** [Nitrokey/nextbox#6]
I've build the qemu-image with "bash build_image.sh" on a ARM64 Debian 10.10 with qemu installed and get the error: "cannot execute binary file: Exec format error"

**Comment by daringer** [comment]
This has only been tested on the x64 architecture, Debian 10.
So I cannot tell what's the reason here, sorry.

A wild guess would be that the call to `qemu-system-aarch64` could lead to this "exec format error" 
(which usually means you are trying to execute a binary that was compiled for another architecture)
